#!/usr/bin/env python3
"""
Build Gemini-compatible agent base templates from Claude Code originals.

Source:      agents/_bases/<name>.md
Destination: agents/_bases-gemini/<name>.md

Conversions:
  - frontmatter `allowed-tools: [...]` -> `tools: [...]`
  - Claude Code tool names -> Gemini tool names (via the table below;
    keep this in sync with skills/using-devtools/references/gemini-tools.md)
  - tools without a Gemini equivalent are DROPPED with a comment note
  - body (markdown content after frontmatter) is preserved verbatim
  - generation header added so users can spot regenerated files

Idempotent: running twice with no source changes produces no diff.

Usage:
  python scripts/build-gemini-agents.py
  python scripts/build-gemini-agents.py --check    # exit non-zero if outputs are stale
"""

from __future__ import annotations

import sys
from pathlib import Path

# Source-of-truth tool mapping (must match references/gemini-tools.md).
# None means "no equivalent" -- entry is dropped from the converted list.
CC_TO_GEMINI = {
    "Read": "read_file",
    "Write": "write_file",
    "Edit": "replace",
    "Glob": "glob",
    "Grep": "grep_search",
    "Bash": "run_shell_command",
    "Agent": None,                    # no direct Gemini equivalent in v1
    "Skill": "activate_skill",
    "Task": "tracker_create_task",    # experimental on Gemini
    "TodoWrite": "write_todos",
    "WebFetch": "web_fetch",
    "WebSearch": "google_web_search",
    "NotebookEdit": None,             # no direct Gemini equivalent
    "AskUserQuestion": "ask_user",
    "EnterPlanMode": "enter_plan_mode",
    "ExitPlanMode": "exit_plan_mode",
}

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "agents" / "_bases"
DST_DIR = REPO_ROOT / "agents" / "_bases-gemini"

GENERATED_HEADER = (
    "<!-- Generated by scripts/build-gemini-agents.py from agents/_bases/{name}.md -->\n"
    "<!-- Do not edit this file directly. Edit the source MD and re-run the script. -->\n"
)


def split_frontmatter(text: str) -> tuple[list[str], str]:
    """Return (frontmatter_lines_without_delimiters, body)."""
    if not text.startswith("---\n"):
        return [], text
    end = text.find("\n---", 4)
    if end < 0:
        return [], text
    fm = text[4:end].splitlines()
    body = text[end + 4 :].lstrip("\n")
    return fm, body


def convert_frontmatter(fm_lines: list[str]) -> list[str]:
    """Convert one base-template frontmatter block to Gemini's shape."""
    out: list[str] = []
    for line in fm_lines:
        stripped = line.strip()
        # Rename `allowed-tools: [...]` -> `tools: [...]` and translate tool names.
        if stripped.startswith("allowed-tools:"):
            payload = stripped.split(":", 1)[1].strip()
            if payload.startswith("[") and payload.endswith("]"):
                inner = payload[1:-1]
                cc_tools = [t.strip() for t in inner.split(",") if t.strip()]
                gemini_tools: list[str] = []
                dropped: list[str] = []
                for t in cc_tools:
                    mapped = CC_TO_GEMINI.get(t)
                    if mapped is None:
                        if t in CC_TO_GEMINI:
                            dropped.append(t)
                        else:
                            print(f"  warn: unknown tool '{t}' -- preserving verbatim")
                            gemini_tools.append(t)
                    else:
                        gemini_tools.append(mapped)
                out.append(f"tools: [{', '.join(gemini_tools)}]")
                if dropped:
                    out.append(f"# dropped (no Gemini equivalent): {', '.join(dropped)}")
            else:
                print(f"  warn: block-style allowed-tools not converted on line: {line!r}")
                out.append(line)
        else:
            out.append(line)
    return out


def convert_one(src: Path) -> str:
    """Return the converted file content for a single source agent."""
    text = src.read_text(encoding="utf-8")
    fm_lines, body = split_frontmatter(text)
    if not fm_lines:
        return GENERATED_HEADER.format(name=src.stem) + text
    new_fm = convert_frontmatter(fm_lines)
    return (
        GENERATED_HEADER.format(name=src.stem)
        + "---\n"
        + "\n".join(new_fm)
        + "\n---\n\n"
        + body
    )


def build(check_only: bool = False) -> int:
    if not SRC_DIR.is_dir():
        print(f"ERROR: source dir missing: {SRC_DIR}", file=sys.stderr)
        return 2
    DST_DIR.mkdir(parents=True, exist_ok=True)

    sources = sorted(SRC_DIR.glob("*.md"))
    print(f"Building Gemini base agents: {len(sources)} sources -> {DST_DIR}")

    stale = 0
    for src in sources:
        dst = DST_DIR / src.name
        new_content = convert_one(src)
        existing = dst.read_text(encoding="utf-8") if dst.exists() else None
        if existing == new_content:
            print(f"  ok    {src.name} (unchanged)")
        else:
            stale += 1
            if check_only:
                print(f"  STALE {src.name}")
            else:
                dst.write_text(new_content, encoding="utf-8")
                print(f"  wrote {src.name}")

    if check_only and stale > 0:
        print(f"\n{stale} files are stale. Run without --check to regenerate.")
        return 1
    print(f"\nDone. {stale} file(s) {'would be ' if check_only else ''}updated.")
    return 0


if __name__ == "__main__":
    sys.exit(build(check_only="--check" in sys.argv))
